"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 D:\Masjid\fajar-baitullah\public\models\scene.gltf -t 
*/

import React from "react";
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";

interface GLTFAction extends THREE.AnimationClip {}

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh;
  };
  materials: {
    lambert2: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>>;

export default function Mosque(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/scene.gltf") as GLTFResult;
  const baseColorTexture = useTexture("models/textures/lambert2_baseColor.png");
  baseColorTexture.flipY = false;
  const textureMaterial = new THREE.MeshStandardMaterial({
    map: baseColorTexture,
  });
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={textureMaterial} scale={0.05} />
    </group>
  );
}

useGLTF.preload("/models/scene.gltf");
