import type { Metadata } from "next";
import { openSans400 } from "@/assets/fonts";
import { Footer, Navbar } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fajar Baitullah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body className={openSans400.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
